### ISSUE TITLE
Some trouble with the WND USE ICON FILE

### ISSUE THREAD

**Issue by PierreTavenard** [miyako/4d-plugin-window-control#1]
Hello miyako,

Thank you very much for your work! i use **WND Is minimized** and **WND RESTORE** successfully now.
It's really usefull.

I have some trouble with the **WND USE ICON FILE** command.
Wich type of file does it accept ? i tried with a .ico file. The only result is : the 4D icon disappears of the window.

No clue, how to do it.

I'm on Windows 10, 4Dv16r6

**Comment by miyako** [comment]
the plugin simply calls SHGetFileInfo to get SHGFI_LARGEICON|SHGFI_ICON 
it is an old API that obtains 32x32 or 16x16 icons.
maybe your .ico is too large.

note to self: SHGetImageList can get 48x48 or 256x256

**Comment by PierreTavenard** [comment]
Thanks for your reply, 
My .ico file contains, 32x32 and 16x16 images. So idon't know why it doesn't work.
Could it be possible for you to upload a .ico example ?

**Comment by miyako** [comment]
it would make more sense for you to send me your file, don't you think? 
😊

**Comment by PierreTavenard** [comment]
i sent it to you by email.
That's the logo of our company. I prefere to not post it here.

**Comment by miyako** [comment]
I don't see any in my inbox in case you are wondering. 
And it doesn't have to be your real icon file, 
just something that can reproduce your issue.

**Comment by PierreTavenard** [comment]
[Logo.zip](https://github.com/miyako/4d-plugin-window-control/files/2219323/Logo.zip)

Here a .ico with the same problem

**Comment by miyako** [comment]
should be fixed now.

**Comment by PierreTavenard** [comment]
Yes, it works, thanks Miyako !
