### ISSUE TITLE
SDI Windows title bar color

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-window-control#3]
Hi,

it would be nice to set the windows title bar color for 4D SDI Windows, if possible. Also to set the zoom and hide buttons inside the windows title bar for SDI windows visible or hide

Thanks Armin

**Comment by miyako** [comment]
have you researched on this subject?

it seems like we are strongly discouraged from attempting to customise the caption area.

http://www.it-quants.com/Blogs/tabid/83/EntryId/53/Win32-SDK-how-to-change-the-title-bar-color-title.aspx

http://www.geekswithblogs.net/kobush/articles/CustomBorderForms.aspx

https://docs.microsoft.com/ja-jp/windows/win32/dwm/customframe

https://stackoverflow.com/questions/39261826/change-the-color-of-the-title-bar-caption-of-a-win32-application

**Comment by ArminDeeg** [comment]
Oh, thanks 
I thought it was just a flag

Armin
